name: "ReviewCheck"

on:
  workflow_dispatch:
  pull_request:
    types: [synchronizer, opened, reopened]
  pull_request_review:
    types: [submitted]
  check_run:
    types: [created]

permissions:
  actions: write
  contents: write
  pull-requests: write

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: get the count of requested reviewers 1
        run: |
          len=$(echo '${{ toJson(github.event.pull_request.requested_reviewers) }}' | jq '. | length')
          echo "len = $len"
      - name: unique approvals
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          pr_num=$(jq --raw-output .pull_request.number "$GITHUB_EVENT_PATH")
          raw=$(gh api \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            /repos/${githubrepository}/pulls/${pr_num}/reviews)

          users=()
          for row in $(echo "${raw}" | jq -r '.[] | @base64'); do
            _jq() {
              echo "${row}" | base64 --decode | jq -r "${1}"
            }
            state=$(_jq '.state')

            user=$(_jq '.user.login')

            case $state in
            'APPROVED')
              users+=("${user}")
              ;;
            'CHANGES_REQUESTED')
              # shellcheck disable=SC2206
              users=(${users[@]/${user}/})
              ;;
            *) ;;
            esac
          done

          declare -A uniq_tmp
          for item in "${users[@]}"; do
            uniq_tmp[$item]=0
          done

          branch="${{ github.event.pull_request.head.ref }}"

          state=failure

          if [[ $branch = test* ]] && [[ ${#uniq_tmp[@]} -ge 1 ]]; then
            state=success
          fi

          if [[ $branch = flight* ]] && [[ ${#uniq_tmp[@]} -ge 2 ]]; then
            state=success
          fi

          echo "state           :" "${state}"
          echo "branch          :" "${branch}"
          echo "total count     :" "${#users[@]}"
          echo "unique count    :" "${#uniq_tmp[@]}"
          echo "unique approval :" "${!uniq_tmp[@]}"

          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GH_TOKEN }}"\
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/${{ github.repository }}/statuses/${{ github.event.pull_request.head.sha }} \
            -d '{"state":"'"${state}"'","target_url":"https://www.notion.so/respond/Respond-io-Git-Workflows-c1e4bcd290094236a6a6e78b06107f42?pvs=4#4edd313ee4f54f85b130864439ce417d","description":"To merge the flight branch into the master branch, approval from all the code owners is necessary.","context":"review-enforcer"}'
