name: "ReviewCheck"

on:
  workflow_dispatch:
  pull_request:
    types: [synchronizer,opened,reopened]
  pull_request_review:
    types: [submitted]
  check_run:
    types: [created]

permissions:
  actions: write
  contents: write
  pull-requests: write

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: fake
        run: echo 'hello world'
      - name: get the count of requested reviewers
        run: |
          # len=$(echo $requested_reviewers | jq '. | length')
          len=$(echo '${{ toJson(github.event.pull_request.requested_reviewers) }}' | jq '. | length')
          echo "len = $len"
      - uses: actions/create-outputs@v0.0.0-fake
        id: test
      - uses: LouisBrunner/checks-action@v1.6.0
        if: always()
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          name: Test XYZ
          conclusion: ${{ job.status }}
          output: |
            {"summary":"${{ steps.test.outputs.summary }}"}
      - name: TestFail
        run: exit 1
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v35
      - name: List all changed files
        run: |
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            echo "$file was changed"
          done
