name: "ReviewCheck"

on:
  workflow_dispatch:
  pull_request:
    types: [synchronizer,opened,reopened]
  pull_request_review:
    types: [submitted]
  check_run:
    types: [created]

permissions:
  actions: write
  contents: write
  pull-requests: write

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: unique approvals
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          pr_num=$(jq --raw-output .pull_request.number "$GITHUB_EVENT_PATH")
          raw=$(gh api \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            /repos/${{ github.repository }}/pulls/${pr_num}/reviews)

          users=()

          for row in $(echo "${raw}" | jq -r '.[] | @base64'); do
            _jq() {
              echo ${row} | base64 --decode | jq -r ${1}
            }
            state=$(_jq '.state')

            user=$(_jq '.user.login')

            if [[ $state == 'APPROVED' ]]; then
              users+=(${user})
            fi

            if [[ $state == 'CHANGES_REQUESTED' ]]; then
              echo "remove: $user"
              users=(${users[@]/$user/})
            fi
          done

          echo '+++++++++++++++++++++++++++++++++++++++++++'

          declare -A uniq_tmp

          for ip in "${users[@]}"; do
            uniq_tmp[$ip]=0 # assigning a placeholder
          done

          echo "unique approval: ${!uniq_tmp[@]}" # only the keys
          echo "approvals count: ${#uniq_tmp[@]}"

          branch="${{ github.event.pull_request.head.ref }}"
          echo "branch         : ${branch}"

          state=failure

          if [[ $branch =~ test. ]] && [[ ${#uniq_tmp[@]} -ge 1 ]]; then
            state=success
          fi

          if [[ $branch =~ flight. ]] && [[ ${#uniq_tmp[@]} -ge 2 ]]; then
            state=success
          fi

          echo "state: $state"

          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GH_TOKEN }}"\
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/${{ github.repository }}/statuses/${{ github.event.pull_request.head.sha }} \
            -d '{"state":"'"${state}"'","target_url":"https://example.com/build/status","description":"The build is TODO!","context":"review-enforcer"}'

