name: "ApprovalStatus"

on:
  workflow_dispatch:
  pull_request:
    types: [synchronize, opened, reopened]
  pull_request_review:
    types: [submitted]
  # check_run:
  #   types: [created]

permissions:
  #   actions: write
  #   contents: write
  #   pull-requests: write
  #   checks: write
  statuses: write

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  main:
    runs-on: ubuntu-latest
    if: github.event.pull_request.base.ref == 'master'
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: approval status
        env:
          GH_TOKEN: ${{ github.token }}

          HOTFIX_PREFIX: ${{ vars.CHECK_HOTFIX_PREFIX }}
          HOTFIX_MIN_APPROVALS: ${{ vars.CHECK_HOTFIX_MIN_APPROVALS }}

          FLIGHT_PREFIX: ${{ vars.CHECK_FLIGHT_PREFIX }}
          FLIGHT_MIN_APPROVALS: ${{ vars.CHECK_FLIGHT_MIN_APPROVALS }}

          TARGET_URL: ${{ vars.CHECK_TARGET_URL }}
          DESCRIPTION: ${{ vars.CHECK_DESCRIPTION }}
          CONTEXT: ${{ vars.CHECK_NAME }}
        run: bash ./.github/scripts/review-check.sh
