name: "ApprovalStatus"

on:
  workflow_dispatch:
  pull_request:
    types: [synchronizer, opened, reopened]
  pull_request_review:
    types: [submitted]
  # check_run:
  #   types: [created]

permissions:
  actions: write
  contents: write
  pull-requests: write
  checks: write
  statuses: write

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: approval status
        env:
          GH_TOKEN: ${{ github.token }}

          HOTFIX_PREFIX: ${{ vars.CHECK_HOTFIX_PREFIX }}
          HOTFIX_MIN_APPROVALS: ${{ vars.CHECK_HOTFIX_MIN_APPROVALS }}

          FLIGHT_PREFIX: ${{ vars.CHECK_FLIGHT_PREFIX }}
          FLIGHT_MIN_APPROVALS: ${{ vars.CHECK_FLIGHT_MIN_APPROVALS }}

          TARGET_URL: ${{ vars.CHECK_TARGET_URL }}
          DESCRIPTION: ${{ vars.CHECK_DESCRIPTION }}
          CONTEXT: ${{ vars.CHECK_NAME }}
        run: |
          pr_num=$(jq --raw-output .pull_request.number "$GITHUB_EVENT_PATH")
          raw=$(gh api \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            /repos/${{ github.repository }}/pulls/${pr_num}/reviews)

          users=()
          for row in $(echo "${raw}" | jq -r '.[] | @base64'); do
            _jq() {
              echo "${row}" | base64 --decode | jq -r "${1}"
            }
            state=$(_jq '.state')

            user=$(_jq '.user.login')

            case $state in
            'APPROVED')
              users+=("${user}")
              ;;
            'CHANGES_REQUESTED')
              # shellcheck disable=SC2206
              users=(${users[@]/${user}/})
              ;;
            *) ;;
            esac
          done

          declare -A uniq_tmp
          for item in "${users[@]}"; do
            uniq_tmp[$item]=0
          done
          approved_count="${#uniq_tmp[@]}"
          total_count=$(echo '${{ toJson(github.event.pull_request.requested_reviewers) }}' | jq '. | length')

          branch="${{ github.event.pull_request.head.ref }}"

          state=failure

          if [[ $branch = ${HOTFIX_PREFIX}* ]] && [[ ${approved_count} -ge $HOTFIX_MIN_APPROVALS ]]; then
            state=success
          fi

          if [[ $branch = ${FLIGHT_PREFIX}* ]] && [[ ${approved_count} -ge $FLIGHT_MIN_APPROVALS ]]; then
            state=success
          fi

          # ### [ DEBUG ] ### #
          echo "state           :" "${state}"
          echo "branch          :" "${branch}"
          echo "total count     :" "${#users[@]}"
          echo "xotal count     :" "${total_count}"
          echo "unique count    :" "${#uniq_tmp[@]}"
          echo "unique approval :" "${!uniq_tmp[@]}"
          # ###################

          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${GH_TOKEN}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/${{ github.repository }}/statuses/${{ github.event.pull_request.head.sha }} \
            -d "{\"state\":\"${state}\",\"target_url\":\"${TARGET_URL}\",\"description\":\"${DESCRIPTION}\",\"context\":\"${CONTEXT}\"}"
